from typing import List, TypedDict

class GraphState(TypedDict):
    """
    Represents the state of our graph.
    """
    question: str          # User's initial question
    documents: List[str]   # Markdown chunks retrieved from the DB
    generation: str        # Final answer generated by the LLM
    search_count: int      # Counter to prevent infinite loops